name: Deploy to Azure App Service
on:
  push:
    branches: [ master ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
 
    steps:
      - uses: actions/checkout@v4
 
      # If you need to build, uncomment one section:
 
      # .NET
      - uses: actions/setup-dotnet@v4
        with:
           dotnet-version: '8.0.x'
      - run: dotnet restore
      - run: dotnet publish MicrosoftIdentityAsgSchulz/MicrosoftIdentityAsgSchulz.csproj -c Release -o ./publish
 
      # Node
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      # - run: npm ci
      # - run: npm run build
 
      # PHP (no build)
      # - run: php -v
 
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: >
            {"clientId":"${{ secrets.AZURE_CLIENT_ID }}",
             "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
             "tenantId":"${{ secrets.AZURE_TENANT_ID }}",
             "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}"}
 
      - name: Deploy to App Service
        uses: azure/webapps-deploy@v3
        with:
9          package: ./publish            # For .NET
          # Use ./dist for Node, or "." for PHP if no build