name: Deploy ASP.NET MVC to Azure Web App

on:
  push:
    branches: [ "master" ]        # <-- change to "master" if your repo uses master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: wp1-17225389-fa25        # <-- your App Service name
  PROJECT_FILE: MicrosoftIdentityAsgSchulz/MicrosoftIdentityAsgSchulz.csproj

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore "${{ env.PROJECT_FILE }}"

      - name: Publish
        run: dotnet publish "${{ env.PROJECT_FILE }}" -c Release -o "${{ github.workspace }}/publish"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/publish
