name: Deploy ASP.NET MVC to Azure

on:
  push:
    branches: [ "master" ]   # change to "main" if your default branch is main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: wp1-17225389-fa25
  PROJECT_PATH: MicrosoftIdentityAsgSchulz/MicrosoftIdentityAsgSchulz.csproj
  PUBLISH_DIR: ./publish

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # no id-token needed when using 'creds'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore "${{ env.PROJECT_PATH }}"

      - name: Publish
        run: dotnet publish "${{ env.PROJECT_PATH }}" -c Release -o "${{ env.PUBLISH_DIR }}"

      # Secret-based login (uses your 4 separate secrets)
      - name: Azure login (Service Principal with client secret)
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId":        "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret":    "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId":  "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId":        "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.PUBLISH_DIR }}
