name: Deploy App Service (Code + Container Slot)

on:
  push:
    branches: [ "master" ] # <-- change to "main" if your repo uses main
  workflow_dispatch:
    inputs:
      target:
        description: "What to deploy?"
        required: true
        default: "code"
        type: choice
        options: [ "code", "container" ]
      image_name:
        description: "Docker image name (for container path)"
        required: false
        default: "wp1app"
        type: string

env:
  # Build settings
  DOTNET_VERSION: "8.0.x"
  PROJECT_PATH: "MicrosoftIdentityAsgSchulz/MicrosoftIdentityAsgSchulz.csproj"
  PUBLISH_DIR: "./publish"

  # Your Azure resources
  RG: "rg-WebProgramming1-Fall2025-bs"
  WEBAPP: "wp1-17225389-fa25"
  SLOT: "container-demo"

  # TODO: set to your class ACR name (no ".azurecr.io"), e.g., classfa25acr
  ACR_NAME: "TODO_PUT_ACR_NAME_HERE"

jobs:
  # ---------------------------
  # CODE DEPLOY (Production)
  # ---------------------------
  build_code:
    name: Build (.NET) for Production
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'code')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore "${{ env.PROJECT_PATH }}"

      - name: Build
        run: dotnet build "${{ env.PROJECT_PATH }}" -c Release --no-restore

      - name: Publish
        run: dotnet publish "${{ env.PROJECT_PATH }}" -c Release --no-build -o "${{ env.PUBLISH_DIR }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{ env.PUBLISH_DIR }}

  deploy_code:
    name: Deploy to App Service (Production)
    runs-on: ubuntu-latest
    needs: build_code
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'code')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ${{ env.PUBLISH_DIR }}

      - name: Azure login (Service Principal - client secret)
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId":        "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret":    "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId":  "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId":        "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Show Azure context
        run: |
          az account show -o table
          az webapp show -g "${{ env.RG }}" -n "${{ env.WEBAPP }}" -o table

      - name: Inspect publish directory
        run: |
          echo "Publishing from: ${{ env.PUBLISH_DIR }}"
          ls -la "${{ env.PUBLISH_DIR }}"
          du -sh "${{ env.PUBLISH_DIR }}"

      - name: Deploy to App Service (Production)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP }}
          package: ${{ env.PUBLISH_DIR }}

  # ---------------------------
  # CONTAINER DEPLOY (Slot)
  # ---------------------------
  build_and_deploy_container:
    name: Build & Deploy Container to Slot
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'container'
    permissions:
      contents: read
      id-token: write
    env:
      IMAGE_NAME: ${{ github.event.inputs.image_name }}
    steps:
      - name: Check ACR name is set
        run: |
          if [ -z "${{ env.ACR_NAME }}" ] || [ "${{ env.ACR_NAME }}" = "TODO_PUT_ACR_NAME_HERE" ]; then
            echo "ERROR: Set env.ACR_NAME at top of workflow to your ACR name (no .azurecr.io)."
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (Service Principal - client secret)
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId":        "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret":    "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId":  "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId":        "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Build Docker image
        run: |
          TAG=${{ github.sha }}
          docker build -f Dockerfile -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$TAG .
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: ACR Login (RBAC)
        run: az acr login --name $ACR_NAME

      - name: Push image to ACR
        run: docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${TAG}

      - name: Point slot at image (Managed Identity)
        run: |
          az webapp config container set \
            -g "${{ env.RG }}" -n "${{ env.WEBAPP }}" --slot "${{ env.SLOT }}" \
            --docker-custom-image-name "$ACR_NAME.azurecr.io/$IMAGE_NAME:${TAG}" \
            --docker-registry-server-url "https://$ACR_NAME.azurecr.io"
          az webapp config set -g "${{ env.RG }}" -n "${{ env.WEBAPP }}" --slot "${{ env.SLOT }}" \
            --generic-configurations '{"acrUseManagedIdentityCreds": true}'
          az webapp config appsettings set -g "${{ env.RG }}" -n "${{ env.WEBAPP }}" --slot "${{ env.SLOT }}" \
            --settings WEBSITES_PORT=8080

      - name: Restart slot
        run: az webapp restart -g "${{ env.RG }}" -n "${{ env.WEBAPP }}" --slot "${{ env.SLOT }}"

      - name: Show container config
        run: az webapp config container show -g "${{ env.RG }}" -n "${{ env.WEBAPP }}" --slot "${{ env.SLOT }}" -o jsonc
