name: Deploy ASP.NET MVC to Azure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: wp1-17225389-fa25
  DOTNET_VERSION: '8.0.x'
  PROJECT_PATH: ./MicrosoftIdentityAsgSchulz/MicrosoftIdentityAsgSchulz.csproj  # <-- change if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - run: dotnet restore ${{ env.PROJECT_PATH }}
      - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o publish

      # ---- Choose ONE auth method below ----
      # A) Service Principal JSON (secret name: AZURE_CREDENTIALS)
      - name: Azure login (SP)
        if: ${{ secrets.AZURE_CREDENTIALS != '' }}
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # B) OIDC (three secrets: AZURE_CLIENT_ID / TENANT_ID / SUBSCRIPTION_ID)
      - name: Azure login (OIDC)
        if: ${{ secrets.AZURE_CREDENTIALS == '' }}
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: publish
